apiVersion: v1
kind: Pod
metadata:
  name: hellok8s
spec:
  containers:
  - name: hellok8s-container
    image: baikal0716/hellok8s:v5
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: hellok8s-secret
            key: DB_PASSWORD

